spring.application.name=hello
spring.thymeleaf.suffix=.jsp
spring.thymeleaf.prefix=classpath:/templates
spring.datasource.url=jdbc:mysql://8.141.93.221:3306/signproject?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/signproject?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
#spring.datasource.password=1234567890lzk
spring.datasource.password=RrhjY971
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8085
